example_events = [
    {
        "id": 1,
        "name": "Welcome Day",
        "description": "The Welcome Day of GDG Algiers is a chance for new members to know more about our activities and events",
        "date": "Tuesday, November 14, 2023",
        "time": "12:00 AM – 4:00 PM GMT+1",
        "location": "Ecole Nationale Supérieure d'Informatique (Ex. INI), Algiers, Algeria",
        "image": "https://res.cloudinary.com/startup-grind/image/fetch/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/https://res.cloudinary.com/startup-grind/image/upload/c_fill%2Cdpr_2.0%2Cf_auto%2Cg_center%2Cq_auto:good/v1/gcs/platform-data-goog/event_banners/gdev-eccosystems-bevy-chapters-thumbnail_x4z1EBy.png",
    },
    {
        "id": 2,
        "name": "Devfest'23 Talks",
        "description": "A serie of tech talks",
        "date": "Nov 30",
        "time": "6:00 – 11:00 PM",
        "location": "Online",
        "image": "https://res.cloudinary.com/startup-grind/image/fetch/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/https://res.cloudinary.com/startup-grind/image/upload/c_fill%2Cdpr_2.0%2Cf_auto%2Cg_center%2Cq_auto:good/v1/gcs/platform-data-goog/event_banners/gdev-eccosystems-bevy-chapters-thumbnail_x4z1EBy.png",
    },
    {
        "id": 3,
        "name": "GDG Algiers School",
        "description": "GDG School is coming with a new format that can adapt to the members that can't attend, with bootcamps with different fields, projects and challenges.",
        "date": "December 8 – 9, 2023",
        "time": "9:00 AM – 6:00 PM GMT+1",
        "location": "Ecole Nationale Supérieure d'Informatique (Ex. INI), Algiers, Algeria",
        "image": "https://res.cloudinary.com/startup-grind/image/fetch/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/https://res.cloudinary.com/startup-grind/image/upload/c_fill%2Cdpr_2.0%2Cf_auto%2Cg_center%2Cq_auto:good/v1/gcs/platform-data-goog/event_banners/gdev-eccosystems-bevy-chapters-thumbnail_x4z1EBy.png",
    },
]


example_participants = [
    {
        "firstName": "John",
        "lastName": "Doe",
        "email": "john@example.com",
        "phone": "123-456-7890",
        "isStudent": True,
        "university": "ABC University",
        "eventId": 1,
    },
    {
        "firstName": "Alice",
        "lastName": "Smith",
        "email": "alice@example.com",
        "phone": "987-654-3210",
        "isStudent": False,
        "eventId": 2,
    },
    {
        "firstName": "Emma",
        "lastName": "Johnson",
        "email": "emma@example.com",
        "phone": "555-555-5555",
        "isStudent": True,
        "university": "XYZ College",
        "eventId": 1,
    },
    {
        "firstName": "Michael",
        "lastName": "Brown",
        "email": "michael@example.com",
        "phone": "444-333-2222",
        "isStudent": False,
        "eventId": 3,
    },
    {
        "firstName": "Sophia",
        "lastName": "Lee",
        "email": "sophia@example.com",
        "phone": "777-888-9999",
        "isStudent": True,
        "university": "LMN University",
        "eventId": 2,
    },
    {
        "firstName": "Daniel",
        "lastName": "Garcia",
        "email": "daniel@example.com",
        "phone": "111-222-3333",
        "isStudent": True,
        "university": "PQR College",
        "eventId": 1,
    },
    {
        "firstName": "Olivia",
        "lastName": "Miller",
        "email": "olivia@example.com",
        "phone": "666-777-8888",
        "isStudent": False,
        "eventId": 2,
    },
    {
        "firstName": "William",
        "lastName": "Wilson",
        "email": "william@example.com",
        "phone": "222-333-4444",
        "isStudent": True,
        "university": "UVW Institute",
        "eventId": 3,
    },
    {
        "firstName": "Imad",
        "lastName": "Fenniche",
        "email": "imadfen20@gmail.com",
        "phone": "222-333-4444",
        "isStudent": True,
        "university": "UVW Institute",
        "eventId": 1,
    },
]
